# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20160124_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='active',
            field=models.BooleanField(default=False, help_text="Unselect if you don't want this page to be visible on the site (irrespective of user permissions)"),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(help_text='A unique identifier for this page. Use lowercase, no spaces.  Forward slash (/) and hyphens (-) are allowed.', max_length=255, unique=True),
        ),
    ]
