# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-07 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('clinic', 'Stretch Clinic'), ('workshop', 'Workshop')], default='clinic', max_length=50)),
                ('short_name', models.CharField(blank=True, help_text='Short name; will be displayed on timetable page.', max_length=50, null=True)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('max_spaces', models.PositiveIntegerField(default=9, help_text='Maximum number of spaces')),
                ('contact_person', models.CharField(default='Alicia Alexandra', max_length=255)),
                ('contact_email', models.EmailField(default='flexibeast@hotmail.com', max_length=254)),
                ('cost', models.DecimalField(decimal_places=2, default=30.0, help_text='Cost (£) per hour', max_digits=8)),
                ('spaces', models.PositiveIntegerField(blank=True, null=True)),
                ('show_on_site', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.Location')),
            ],
        ),
        migrations.AlterField(
            model_name='weeklysession',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=7.5, max_digits=8),
        ),
    ]
