# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StretchClinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('max_participants', models.PositiveIntegerField(blank=True, default=9, help_text='Leave blank if no max number of participants', null=True)),
                ('contact_person', models.CharField(default='Alicia Alexandra', max_length=255)),
                ('contact_email', models.EmailField(default='flexibeast@hotmail.com', max_length=254)),
                ('cost', models.DecimalField(decimal_places=2, default=7.0, help_text='Cost (£) per hour', max_digits=8)),
                ('spaces', models.PositiveIntegerField()),
                ('show_on_site', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.Location')),
            ],
        ),
    ]
