# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-13 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flex_bookings', '0010_auto_20150926_2225'),
        ('timetable', '0003_auto_20150926_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('map_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('day', models.CharField(choices=[('01MON', 'Monday'), ('02TUE', 'Tuesday'), ('03WED', 'Wednesday'), ('04THU', 'Thursday'), ('05FRI', 'Friday'), ('06SAT', 'Saturday'), ('07SUN', 'Sunday')], max_length=5)),
                ('time', models.TimeField()),
                ('description', models.TextField(blank=True, default='')),
                ('max_participants', models.PositiveIntegerField(blank=True, default=9, help_text='Leave blank if no max number of participants', null=True)),
                ('contact_person', models.CharField(default='Alicia Alexandra', max_length=255)),
                ('contact_email', models.EmailField(default='flexibeast@hotmail.com', max_length=254)),
                ('cost', models.DecimalField(decimal_places=2, default=7.0, max_digits=8)),
                ('full', models.BooleanField(default=False)),
                ('block_info', models.TextField(blank=True, null=True)),
                ('event_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flex_bookings.EventType')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.Location')),
            ],
            options={
                'ordering': ('day', 'time'),
            },
        ),
        migrations.AlterField(
            model_name='session',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, default=9, help_text='Leave blank if no max number of participants', null=True),
        ),
    ]
