# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-28 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20160428_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='weeklysession',
            options={'ordering': ('day', 'time')},
        ),
        migrations.AlterField(
            model_name='weeklysession',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
