# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-28 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20160428_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklysession',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.Location'),
        ),
    ]
