# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-28 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20160428_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='map_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
